### ISSUE TITLE
Create a .draft command

### ISSUE THREAD

**Issue by otterHooligan** [MLROOTC/UmpBot#15]
Command should:

- accept team and player name as input
- create a background template
- add team logo
- add player name
- add round/pick number
- add positions
- add FCB stats (if applicable)
- send to discord

Example: https://media.discordapp.net/attachments/597114169514393610/787504330383032360/file.jpg

Format: .draft OAK; Dottie

**Comment by jay9909** [comment]
> Format: .draft OAK; Dottie

I've already ~~tampered~~ drafted them smh
